basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: A modern and robust Content Management System API built with Go
  title: GoRecta CMS API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
